### ISSUE TITLE
Javaソースコードの体裁

### ISSUE THREAD

**Issue by kacchi** [ymdpn/add#4]
正しく体裁を整えましょう。
正しくない体裁は、以下のような問題が生じます。
* 読みにくい->不具合の原因
* conflictが発生する原因になる->時間の無駄・コミット履歴が汚くなる

また、indentは、4spaceでやりましょう。（これはチームによって異なる場合があります）

**Comment by ymdpn** [comment]
フォーマッターで修正しました。
