### ISSUE TITLE
import ...*

### ISSUE THREAD

**Issue by kacchi** [ymdpn/add#6]
https://github.com/ymdpn/add/blob/3f4a0b3335da93505523034005579ffaf1650229/src/main/java/com/example/Add.java#L2

賛否両論かもしれませんが、一部のケースを除き、importする場合に*を使うのは好まれません。
FQCNで指定しておきましょう。
Eclipseを使っているならば、 `Organize Imports` すればよしなにやってくれます。

**Comment by ymdpn** [comment]
修正しました。
